"""Add profile fields to user

Revision ID: c7e8f9d0g1h2
Revises: b9f4d9d8f4c1
Create Date: 2024-01-17 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7e8f9d0g1h2'
down_revision = 'b9f4d9d8f4c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(150), nullable=True))
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('country', sa.String(100), nullable=True))
        batch_op.add_column(sa.Column('profile_image', sa.String(255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_image')
        batch_op.drop_column('country')
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
